### ISSUE TITLE
hpoliced duplicates HTTPolice code

### ISSUE THREAD

**Issue by vfaronov** [activesphere/httpolice-devtool#1]
In order to process the HAR format, hpoliced currently embeds code copied from HTTPolice itself.

This is not only bad for maintainability; it also leads to subtle bugs. For example, the [`Unavailable`](https://github.com/activesphere/httpolice-devtool/blob/772f5658c643387e43f4ffeaa8f285ed2b8a6931/hpoliced/hpoliced/helpers.py#L35) object is supposed to be a singleton, and your new instance confuses HTTPolice, leading to spurious errors such as [1037](http://pythonhosted.org/HTTPolice/notices.html#1037) on [some sites](http://vasiliy.faronov.name/).

Of course, the problem is that the [HTTPolice API](http://httpolice.readthedocs.io/en/stable/api.html) does not expose a function to process a HAR file. I can add such a function in the next release.

But for now, I suggest that you simply do the following:

```
from httpolice.inputs.har import _process_entry
```

instead of defining your own `_process_entry` (and `_process_request` etc.) functions. I promise not to break the `_process_entry` interface for a while.

**Comment by shinderohitt** [comment]
Thanks @vfaronov for bringing this up. I was confused between the choice of copying a bunch of code and importing a `_`function. Fixing this in a bit.
