### ISSUE TITLE
Wrong filtering logic in hpoliced

### ISSUE THREAD

**Issue by vfaronov** [activesphere/httpolice-devtool#2]
hpoliced uses the following snippet when checking exchanges:

```
if any(notice.severity > 1
       for resp in exch.responses       # We only care about responses
       for notice in resp.notices):
    bad_exchanges.append(exch)
```

This code looks like it was copied from the [API example](http://httpolice.readthedocs.io/en/stable/api.html#example), which shows how to skip exchanges that have no _errors_ in _responses_.

I’m not sure if you intended hpoliced to work like that.

It doesn’t actually work like that, because `notice.severity > 1` is always true. Severity is an enumeration, not an integer. You have to compare to `httpolice.Severity.comment`, as the documentation shows.

But personally, I think this filtering logic is too aggressive. As a user, I may want to see problems that are not “errors”, as well as problems in requests — they shouldn’t be skipped over. Here’s an example of how this could be rewritten:

```
if any(notice.severity > httpolice.Severity.debug
       for msg in [exch.request] + exch.responses
       for notice in msg.notices):
    bad_exchanges.append(exch)
```

It might also be a good idea to document this behavior somewhere.

**Comment by shinderohitt** [comment]
@vfaronov This was definitely a bug. Thanks for mentioning. I meant to come back to this part, but had completely forgotten.
