### ISSUE TITLE
UX bad when devtools docked on the side

### ISSUE THREAD

**Issue by rahuljayaraman** [activesphere/httpolice-devtool#4]
The current UX is decent when docked below, but looks weird when docked on the side.

<img width="560" alt="screen shot 2016-09-19 at 9 12 33 am" src="https://cloud.githubusercontent.com/assets/1269539/18621134/468e46d0-7e49-11e6-8b4f-99912b62d45d.png">

Maybe we should just copy the network tab's master detail view

<img width="588" alt="screen shot 2016-09-19 at 9 14 28 am" src="https://cloud.githubusercontent.com/assets/1269539/18621147/8330e066-7e49-11e6-9f0b-4083a6ee6d72.png">

Perhaps we could probably copy all of their UI (record, clear, listview etc)

**Comment by shinderohitt** [comment]
Hey @rahuljayaraman ,
Check out the changes below

![screen shot 2016-09-20 at 1 47 40 pm](https://cloud.githubusercontent.com/assets/1011044/18662670/f7f2008e-7f38-11e6-8db4-491ec5f78c9d.png)
after loading - first page

![screen shot 2016-09-20 at 1 43 37 pm](https://cloud.githubusercontent.com/assets/1011044/18662731/36c6e8a6-7f39-11e6-8648-26ae59cec874.png)
After selecting a row.

![screen shot 2016-09-20 at 1 44 14 pm](https://cloud.githubusercontent.com/assets/1011044/18662699/143a52d2-7f39-11e6-9f63-cd9cb9475663.png)
regular - bottom, big window
