### ISSUE TITLE
Breaks when clicking on citation links

### ISSUE THREAD

**Issue by vfaronov** [activesphere/httpolice-devtool#6]
When you click on one of those links in the report that link to the standards (like on header names), httpolice-devtools kinda just falls over and becomes a blank page until I restart Chrome.

If I click it with the Ctrl key pressed, the link opens correctly in a new browser tab. Perhaps that could be made the default behavior?

**Comment by shinderohitt** [comment]
**Update :** This is happening on specific sites, will try to resolve it soon 👍 

@vfaronov I am unable to reproduce this on Chrome 56 (macOS Sierra).

To make sure we are talking about the same thing --
I tried clicking on the header links which link to RFC pages (GET, Referer, user-Agent, etc), which correctly opens in new tab without holding Ctrl key 

If it's browser version/platform specific, what is your configuration?
